# Generated by Django 3.1.2 on 2020-11-13 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_shorten',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
