# Generated by Django 3.1.2 on 2020-10-26 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linkurl', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('access_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('access_log_access_datetime', models.DateTimeField(auto_now_add=True)),
                ('access_log_shorten_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='linkurl.link')),
            ],
        ),
    ]
